### ISSUE TITLE
ESXi 7.0 on ARM issues

### ISSUE THREAD

**Issue by cladand** [home-assistant/operating-system#1478]
I'm trying to install haos 6.1 on ESXi 7.0 on ARM.

**HW: Raspberry Pi4 with Samsung SSD 250GB**

1) I tried to use the vmdk linked to a brand new VM and no matter what I change in the parameters, I receive the attached error. I copied the vmdk in the internal SSD vmfs partition.
![WhatsApp Image 2021-07-27 at 12 59 03](https://user-images.githubusercontent.com/88041940/127165926-0367af00-63a1-4382-9e9a-c756e13fa9ab.jpeg)
I also tried to copy the vmdk with vmkfstools -i but same problem.

2) I tried to use the ESXi OVA, but it gives me a VMX compatibility error.
How can I proceed?

**Comment by agners** [comment]
@cladand  sooo.. works?

**Comment by auanasgheps** [comment]
@agners  nope it doesn't, but by design. I helped @cladand and figured out he was trying to boot [the generic x86/64 image](https://www.home-assistant.io/installation/generic-x86-64) on a Raspberry Pi (ARM) with ESXi. 
The problem is that nobody, at least now, does instruction emulation over virtualization, so will never work unless you'll build an ARM image.

**Comment by agners** [comment]
@auanasgheps yeah that make sense.

Note that this also came up a while ago here: #1050. While it should't be too hard to make a vmdk from a Raspberry Pi built image, the problem will be the boot flow: From what I understand ESXi on ARM uses UEFI boot flow. That is not what our RPi OS builds to currently... Not impossible, but involves certainly some work. Currently this is a bit too niche use case to focus on.
