### ISSUE TITLE
Missing linux-firmware

### ISSUE THREAD

**Issue by Kiron21** [home-assistant/operating-system#1822]
### Describe the issue you are experiencing

Is there any reason, why linux-firmware is not included, especially in x86 Home Assistant OS?

We are talking about 1GB with ALL packeges.

Now it is not possible to use many WiFi, Bluetooth etc. hw in x86 PC platforms and there is no way to download it manualy.

And yes, i mean this is a BUG! :p

Thank you.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

7.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install HASS OS
2. Try insert any piesce of HW

### Anything in the Supervisor logs that might be useful for us?

```txt
No.
```

### Anything in the Host logs that might be useful for us?

```txt
No.
```

**Comment by agners** [comment]
> Is there any reason, why linux-firmware is not included, especially in x86 Home Assistant OS?

What is "linux-firmware"? In buildroot, the build system used to build Home Assistant OS, linux-firmware consists of dozens of sub-packages (see https://github.com/buildroot/buildroot/blob/master/package/linux-firmware/linux-firmware.mk). Many make no sense on x86-64 since they are for ARM. There is no "all firmware" package.

It has its upside: It allows to create small Linux distributions for small systems (like ARM devices). The downside being that every firmware need to be enabled manually...

> Try insert any piesce of HW

We have support for more and more WiFi hardware. Any hardware on my desk works :wink: 

> We are talking about 1GB with ALL packeges.

Oh wow, that is rather big! Our rootfs partition is limited to 256MB (although it is compressed, so more is supported)..

Currently I don't have plans to deviate from the current approach: Add firmwares as users need/request it. Please create a new issue with the device you are looking support for.

**Comment by Kiron21** [comment]
Hi.

I am talking about x86 platform. Limitation to 256MB have no sense.

HASS OS is useless for PC platform. There is only one way - switch to
normal linux with standard options for hw.

Thank you and bye.

pá 1. 4. 2022 v 0:01 odesílatel Stefan Agner ***@***.***>
napsal:

**Comment by agners** [comment]
> I am talking about x86 platform. Limitation to 256MB have no sense.

Partitioning for all systems is the same.

That still doesn't change the fact that buildroot does not have a generic linux-firmware package.

It is an open source project, so patches welcome :smile: 

> HASS OS is useless for PC platform. There is only one way - switch to
normal linux with standard options for hw.

We try to build a system which fits *most* use cases to run Home Assistant. Typically this is virtual machines and Intel NUC systems. 

We can't support every PC platform, we don't have the team to do that. Home Assistant OS does not try to be Debian Linux.  If you need a generic distribution, use a generic Linux distribution. If your PC is special, using Debian is the right approach.

**Comment by Kiron21** [comment]
OK, I'm understanding. it's your project :)

Thanks and bye.

My planes for weekend:
[image: image.png]

pá 1. 4. 2022 v 9:05 odesílatel Stefan Agner ***@***.***>
napsal:
