### ISSUE TITLE
RPi 4B supports USB boot, shouldn't HA OS

### ISSUE THREAD

**Issue by newyork10023** [home-assistant/operating-system#2039]
### Describe the issue you are experiencing

Installing HA OS latest (8.4) to a RPi 4B (8GB RAM) stalls and fails using a USB SSD.

Booting from USB is now supported and working on RPi.

Booting from SSD is preferred for all but hobby installations.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

8.4

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Followed directions on website but installed to USB SSD.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Unable to retrieve.
```

### Anything in the Host logs that might be useful for us?

```txt
Unable to retrieve.
```

### Additional information

Booting from USB SSD is widely requested functionality.  HA appears to be intended for more than hobby installs.  Installation to USB SSD on RPi is necessary to that functionality.

**Comment by agners** [comment]
We recommend booting from SD card and store all read-write data on SSD using the [data disk feature](https://www.home-assistant.io/common-tasks/os#using-external-data-disk). Since the operating system is on a read-only squashfs partition, this does not cause wear on the SD card, and avoids troubles with booting form SSD.

While we do not recommend booting directly from SSD (since it often causes problems, especially the USB stack in U-Boot), it works for quite some combinations. See also [this community thread](https://community.home-assistant.io/t/installing-home-assistant-on-a-rpi-4b-with-ssd-boot/230948). YMMV.
