### ISSUE TITLE
SHA digest error when importing ova with VMWare Workstation 16

### ISSUE THREAD

**Issue by ioctl2** [home-assistant/operating-system#2121]
### Describe the issue you are experiencing

Importing the Home Assistant OS ova appliance into VMWare Workstation version 16.2.4 build-20089737 fails with this error:
`SHA digest of file home-assistant.vmdk does not match manifest.`

This happens with the following versions of HAOS (note that this includes a recent dev version):
```
haos_ova-8.4.ova
haos_ova-10.0.dev20220907.ova
haos_ova-8.5.ova
```
If I remove the manifest `home-assistant.mf` from the `.ova`, the appliance imports successfully. Also noteworthy is that the appliance imports into Oracle VirtualBox (6.1) and VMWare ESXi (6.7, 7.1) as-is, without error.

The actual checksums are fine. As an example, the haos_ova-8.5 manifest (`home-assistant.mf`) contains these lines:
```
SHA256(home-assistant.ovf)= 64504b3ae7dd5bf32d74187874538bcf2ea204e1ce0cfbbee399e00ed46d4982
SHA256(home-assistant.vmdk)= 12cec555efcb96a675b7b4aab283ae0148f2b8f36a6983c3908b94519b9b7b12

```
When I compute the checksums for the two referenced files, they match:
```
home-assistant.ovf SHA-256: 64504b3ae7dd5bf32d74187874538bcf2ea204e1ce0cfbbee399e00ed46d4982
home-assistant.vmdk SHA-256: 12cec555efcb96a675b7b4aab283ae0148f2b8f36a6983c3908b94519b9b7b12
```

I have searched existing issues to avoid posting a dup, and found some related discussion, but nothing that addresses this specific issue with VMWare Workstation. One such issue was #826 - since fixed/closed - dealing with ESXi import errors, but one commenter reported that this was not yet fixed in relation to Workstation (see https://github.com/home-assistant/operating-system/issues/826#issuecomment-993766392 and https://github.com/home-assistant/operating-system/issues/826#issuecomment-993855319)

Many appliances still use SHA1 for the manifest file, and it made me wonder if perhaps VMWare Workstation only supported that, and not SHA256. There was an issue related to ESXi and the hash function on the nextcloud issue tracker https://github.com/nextcloud/vm/issues/910#issuecomment-673764335 but this was dealing with ESXi and not Workstation, and with an older (5.5) unsupported (https://kb.vmware.com/s/article/51491) release of the hypervisor.
I looked at the manifest of another project (https://gns3.com/software/download-vm) that ships OVA appliance files, and it uses SHA256 hashes, and the OVA imports into Workstation fine, so the same should apply to the HAOS one. Interestingly, they ship a separate OVA files for Workstation/Fusion and ESXi.

[this is my first bug report for this project, so I'd appreciate any pointers if anything is amiss in my report]

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

NA

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Download OVA appliance.
2. Start to import into VMWare Workstation.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

**Comment by agners** [comment]
I remember last time I looked at it that the person mentioned that Workstation didn't work, but since it wasn't a problem for him I did not further investigate (maybe that also was an old VMware Workstation version).

However, the fact that even the latest VMWare Workstation doesn't work is not nice.

> Many appliances still use SHA1 for the manifest file, and it made me wonder if perhaps VMWare Workstation only supported that, and not SHA256.

That is what I assumed first, and if that would be the case I'd almost say let's push VMware to finally support a modern hash algorithm :smile: 

> I looked at the manifest of another project (https://gns3.com/software/download-vm) that ships OVA appliance files, and it uses SHA256 hashes, and the OVA imports into Workstation fine, so the same should apply to the HAOS one. Interestingly, they ship a separate OVA files for Workstation/Fusion and ESXi.

That is an interesting find! I downloaded the file, and indeed it seems to use SHA256 sums, and even in the very same format as Home Assistant OS:

```
SHA256(GNS3 VM.ovf)= 195c52c7ebba790bca27b57ba578f459dde16e0922c22f1a70ab7001a50563e5
SHA256(GNS3_VM-disk1.vmdk)= 7b064e18d64105f8f7ad3fcec642436344149e2894886ae8e471958b6637f680
SHA256(GNS3_VM-disk2.vmdk)= fa1b56566b1585a948c6769b2ba93a9b7b12315584b8f645ed824d087933d3ab
```

```
SHA256(home-assistant.ovf)= 64504b3ae7dd5bf32d74187874538bcf2ea204e1ce0cfbbee399e00ed46d4982
SHA256(home-assistant.vmdk)= f570066d72d4974e93d408a90ee99bb386850d3d06abdf71ac452168833596fb
```

I also checked file endings, the both seem to be UNIX style.

Just to be clear, you are saying that `GNS3 VM.ova` (sha256 hash `d4b15a691c132522d1c88aa62487c0702826addee15b1be32e5f610fc1b6afab`, extracted from `GNS3.VM.VMware.Workstation.2.2.34.zip`) imports fine with VMware Workstation while  HAOS doesn't? Do you import it as zip file or ova (does it make a difference)? 

One thing I notice is that in our case the ova file name is different (e.g. `haos_ova-9.0.rc2.ova`/`home-assistant.mf` to the containing mf file name, while they use the same (`GNS3 VM.ova`/`GNS3 VM.mf`). Seems weird to that this would matter.

**Comment by agners** [comment]
Hm, I see that we do not have `ovf:size` in the file reference section defined, this error suggests this could be the problem:

```
Error: SHA digest of file home-assistant.vmdk does not match manifest
Warning:
 - Wrong file size specified in OVF descriptor for 'home-assistant.vmdk' (specified: -1, actual 518352384).
```

Although it is optional according to spec...

```
<xs:attribute name="size" type="xs:unsignedLong" use="optional">
  <xs:annotation>
    <xs:documentation>
      Size in bytes of the files (if known)
    </xs:documentation>
  </xs:annotation>
</xs:attribute>
```

Can you try adding `ovf:size="518352384"` to the ovf file and see if that imports properly?

**Comment by agners** [comment]
When `ovf:Machine` section is removed the `home-assistant.ovf` successfully validates against `dsp8023_1.0.xsd`, so the XML should by semantically correct and complete. The SHA256 hashes are clearly correct too. I don't see why this is a HAOS issue, this seems to be a VMware Workstation issue to me. Can you open a bug with the VMware folks?

**Comment by agners** [comment]
> Sorry, I am not ready to chase VMWare.

Same here :sweat_smile: 

> But if not, then I would suggest to update the documentation to say that the ova method for Workstation isn't supported.

Works for me.

**Comment by agners** [comment]
Seems there is no way to open a bug report without support agreement. Also, it seems there has been made an attempt int he past (at least [this community forum thread](https://communities.vmware.com/t5/Open-Virtualization-Format-Tool/SHA-digest-of-vmdk-does-not-match-manifest/m-p/2928292#M1706) looks very similar).

**Comment by jens-maus** [comment]
Have you guys tried to import the ova images we at the RaspberryMatic project generate in a similar manner than here? See https://github.com/jens-maus/RaspberryMatic/releases/latest

**Comment by ioctl2** [comment]
[Here](https://twitter.com/mikeroySoft/status/1570161059172077569) is a relevant Twitter exchange that I think is worth pursuing.

**Comment by 0x4d4e** [comment]
I ran into the same issue when generating a Kali-Linux VM Image using https://gitlab.com/kalilinux/build-scripts/kali-vm.

As per the feedback on the Twitter exchange, using a streamOptimized VMDK image seems to cause the issue. Removing `-o streamOptimized` when building the .ova (see https://gitlab.com/kalilinux/build-scripts/kali-vm/-/blob/main/scripts/export-ova.sh) results in a larger image, but it can be imported without issues in VMware Workstation afterwards. Seems this issue has to be fixed by VMware ...

You can also convert an existing streamOptimized vmdk image in an ova (after extracting the tar archive) using qemu-img:

    qemu-img convert -O vmdk input.streamOptimized.vmdk output.vmdk    # no -o streamOptimized

After replacing the original vmdk (using the original name or updating the reverence in the .ovf file) and updating the hash in the manifest file, the .ovf file is imported successfully. See also https://gitlab.com/kalilinux/build-scripts/kali-vm/-/blob/main/scripts/export-ovf.sh for generating the un-streamOptimized output in the .ovf build tool of kali-vm (https://gitlab.com/kalilinux/build-scripts/kali-vm/-/blob/main/scripts/export-ovf.sh).

**Comment by agners** [comment]
@0x4d4e interesting finds, thanks for sharing!

From what I understand the `streamOptimized` option allows sparse files (from at least judging by [this documentation](https://vdc-download.vmware.com/vmwb-repository/dcr-public/ae1a858c-2f59-4a75-b333-f2ddfa631fbd/4ae542fa-c7ec-4713-a3a0-6fef938b03d1/doc/vddkDataStruct.5.3.html)).

For HAOS, the image size increases from 436MB to 923MB (`streamOptimized` to `monolithicSparse`).

For the pure vmdk file currently `monolithicSparse` is used, but there we use zip compression afterwards. Maybe we can use that as well for ovf.

It seems that ovf supports gzip compressed disks, so maybe that is an option. However, it seems that some (other) [VMware products have problem with that](https://anthonyspiteri.net/quick-fix-ovf-package-with-compressed-disks-is-currently-not-supported/) :cold_sweat: 

> As per the feedback on the Twitter exchange

Do you happen to have a link to that thread?

**Comment by 0x4d4e** [comment]
> Do you happen to have a link to that thread?

From @ioctl2 's comment above mine: https://twitter.com/mikeroySoft/status/1570161059172077569

**Comment by ioctl2** [comment]
This is still an issue.

**Comment by pinksocks** [comment]
> This is still an issue.

He is correct.  
Anyone still having the issue, try these instructions:
https://rootedshell.medium.com/failed-to-open-virtual-machine-sha1-digest-of-file-xxxxxxxx779-disk1-vmdk-does-not-match-manifest-7d0d94db4451

STEP 1: Extract the xxxxxxxx.ova file with 7zip.
STEP 2: Delete [xxxxx.mf] manifest file.
STEP 3: Open xxxxxxxxxxxx.ovf File in VMWare.
STEP 4: Virtual Machine Import, Done. 👍

**Comment by agners** [comment]
Yes, this is still a problem, but it is a bug in VMWare Workstation 16. Unfortunately, I was unable to report the bug because I am not a VMware customer. If you have a support agreement with VMWare, please report the issue with VMware.

See https://github.com/home-assistant/operating-system/issues/2121#issuecomment-1246448835.

**Comment by elboulangero** [comment]
I did more research on that one, at https://gitlab.com/kalilinux/build-scripts/kali-vm/-/issues/25#note_1290346720. From what I can see, the issue is not in the `.ovf`, it's in the `.vmdk`. If it's created with vmware tools (eg. `vmware-vdiskmanager`) it imports fine, but if it's created with `qemu-img` for example, it fails with the « _SHA checksum does not match manifest_ » error.

So definitely a bug in VMware, even more after reading the [twitter message](https://twitter.com/mikeroySoft/status/1570161059172077569) from @mikeroysoft that was mentioned above. If vmware do the checksum after converting the disk back and forth, no surprise the checksums don't match... But it might match (by chance) if the disk is decompressed/recompressed using the exact same algorithm and it's deterministic, ie. the disk was created using vmware own tools.
