### ISSUE TITLE
Google Coral device disappears after a while

### ISSUE THREAD

**Issue by FS1961** [home-assistant/operating-system#2254]
### The problem

Google Coral device disappears after a while (randomly) and I have to reboot my HA to get it back. This has been going on ever since I installed the Coral. I use this for Frigate but the HAOS "loses" the Coral, not Frigate. Using terminal I confirm the device is present and also that it is lost.

Example of being present.

<img width="657" alt="Screenshot 2022-12-04 at 8 42 36 AM" src="https://user-images.githubusercontent.com/98458806/205479852-ab16c580-aa73-4ee7-a3a0-2c48aeaacfee.png">

### What version of Home Assistant Core has the issue?

2022.11.5

### What was the last working version of Home Assistant Core?

unknown

### What type of installation are you running?

Home Assistant OS

### Additional information

I am running a MacPro (HighSierra), VirtualBox, HA so this may be unusual situation.I don't have to reboot the MaPro or VirtualBox instance normally to get the Coral back, just the HA so I can only assume this is where the problem is.

**Comment by agners** [comment]
Can you check the host logs when it happens (or `dmesg` in the shell).

Also check the logs of your host system, if the USB device disappears there too. I have seen previous reports of such behavior, and using just a different (root) port of the host device helped.

**Comment by FS1961** [comment]
So I decided to move the VM to a Win10 host running VirtualBox, not the best situation but it's working there. I think the MacPro is just too old running High Sierra so I might just install Debian/Ubuntu and see what happens there.

**Comment by apadua** [comment]
I have an ESX server running a VM of Ubuntu 22.04 LTS. I have passed through a PCI USB controller. I have plugged in my Coral to that. It also disappears after a while - and it's not running Home Assistant - just frigate. Exactly the same as you - it's on lsusb, then it isn't.

I'm assuming this isn't HA specific, and thanks to your thread i now think it isn't ESX issue either (of course, these could be two separate issues altogether). But figured i'd share since this feels odd.

Cheers!

**Comment by rayzorben** [comment]
I came to this thread because it was happening on my rPI4 as well. So I actually moved over to x86_64 completely where I run HA in a virtual machine in unRAID, so completely different setup. The Coral is also disappearing on there at the host level. I had a spare Coral that I know was working and I put that in its place and it STILL loses it. Makes me think it is a kernel issue.

**Comment by edibledog** [comment]
This is happening to me too on proxmox - I don't think its related to HA

root@pve1:~# lsusb
Bus 001 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 009: ID 18d1:9302 Google Inc. 
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 005: ID 12d1:1001 Huawei Technologies Co., Ltd. E161/E169/E620/E800 HSDPA Modem
Bus 002 Device 003: ID 0bda:a725 Realtek Semiconductor Corp. Bluetooth 5.1 Radio
Bus 002 Device 002: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@pve1:~# lsusb
Bus 001 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 005: ID 12d1:1001 Huawei Technologies Co., Ltd. E161/E169/E620/E800 HSDPA Modem
Bus 002 Device 003: ID 0bda:a725 Realtek Semiconductor Corp. Bluetooth 5.1 Radio
Bus 002 Device 002: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
