### ISSUE TITLE
Intel NUC SD Card Reader doesn't work 

### ISSUE THREAD

**Issue by skgsergio** [home-assistant/operating-system#2688]
### Describe the issue you are experiencing

I wanted to move backups to an SD Card instead of the NUC SSD but I've found the module for the SDCard reader is not present on the OS.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Insert an SDCARD
2. See that nothing happens
3. Check dmesg and see that is not being detected.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

### Additional information

```bash
# lspci | grep 10ec:5229
01:00.0 Class ff00: 10ec:5229
# lsmod | grep rtsx_pci

# modprobe rtsx_pci
modprobe: FATAL: Module rtsx_pci not found in directory /lib/modules/6.1.39
```

Kernel module: https://cateee.net/lkddb/web-lkddb/MISC_RTSX_PCI.html

**Comment by YahyaAlfayad** [comment]
I've updated to HA OS 11.3 but the issue still persist. I am using Intel NUC BOXNUC8i3BEK2.

The output of `lspci` command is:

<img width="1018" alt="image" src="https://github.com/home-assistant/operating-system/assets/5686018/a64b823c-6396-4916-8ac6-e38e8355582e">

However, when I insert the SD card, nothing happens. No device added to `/dev` nor `/dev/disk/by-path` and nothing is logged in `dmesg`

According to [this](https://forums.gentoo.org/viewtopic-t-1093376-start-0.html), "MMC block device driver is also needed. Otherwise kernel recognizes the device but doesn't create a device to access it."

Did anyone manage to mount an SD card successfully? if so, can you please help providing the steps to do so?

Many thanks in advance :)
