### ISSUE TITLE
Boot HA on old laptop/notebooks without UEFI (BIOS only)

### ISSUE THREAD

**Issue by foxtime** [home-assistant/operating-system#3058]
### Describe the issue you are experiencing

Please take note or use this manual as instructions! This is a great solution:
https://community.home-assistant.io/t/install-ha-on-old-laptop-without-uefi/407443/38

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

11.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Just try to follow the steps indicated in the instructions and you will understand how easy it is to get HomeAssistant to work on laptops without UEFI that only have BIOS.

### Anything in the Supervisor logs that might be useful for us?

```txt
none
```

### Anything in the Host logs that might be useful for us?

```txt
none
```

**Comment by jscongdon** [comment]
While this solution does allow installation on non-UEFI devices, it does not allow the expected workflow when upgrading the OS. When the OS is first installed, it is set to boot from SLOTA. So it works fine. When an upgrade is performed, the updated OS is installed to SLOTB, and the grub is not updated properly and will proceed to boot to SLOTA instead of SLOTB. You can manually specify the env settings for GRUB; then it will boot correctly. This involves booting the system using a live boot, and manual editing GRUB config. On the next OS upgrade, the upgrade is installed to SLOTA, and at the same time, the GRUB config is overwritten by the upgrade with the default configuration. This appears fine because the new OS is in SLOTA. So, on reboot after the upgrade, you are on the version you just upgraded to. Upon updating to the next OS version, it puts the OS in SLOTB; it will not boot to SLOTB because defaults specify SLOTA and the GRUB is not updated correctly.

So the question is: Why isn't there an OS version that allows for non-UEFI booting?
