### ISSUE TITLE
12.3 and 12.4 has big problems with Raspberry 

### ISSUE THREAD

**Issue by spanzetta** [home-assistant/operating-system#3441]
### Describe the issue you are experiencing

I was experiencing a lot of different problems after had upgraded to 12.3 and situation didn't change after had upgraded to 12.4
My Pi3A+ was totally unstable and with a lot of errors and various issues..
I just downgraded to 12.2 and .magically my sistem is now performing again perfectly (and very stable).

@developers: pls investigate well about what did cause all of these problems when upgrading to 12.3/13.4..
There must be a reason for that

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

12.2

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

Pi3a+

### Steps to reproduce the issue

1.upgrade OS
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No logs
```

### Anything in the Host logs that might be useful for us?

```txt
Too many various errors
```

**Comment by sairon** [comment]
Sorry, but there's too little information in the report. There is couple of issues there are currently unresolved (like RPi 3B bootlooping with some USB devices) and there's an open issue for it. If it boots without any USB devices, it'll be likely that.

For other "various errors", try searching in the issue tracker, otherwise please take your time and fill in all fields in the bug report form and attach logs (or at least screen captures) so you can get a proper help.
